### ISSUE TITLE
Question: How to talk to one of the clients/sessions from an external tokio:task?

### ISSUE THREAD

**Issue by Tigls** [gbaranski/ezsockets#27]
As I see, the session hashmap is encapsulated in the Server struct. I would also need to send requests to the clients from the server side(and wait for the response from the client) based on a channel event from another tokio task(serialport). So I guess it is either 
- make the session hashmap global, covering it with arc-mutex, but the server doesn't accept the mutex type
- somehow pass a channel to the server and serialport task so they can communicate, is this possible?

maybe you could point me to another way, how to communicate with the server instance, or would I need to write something custom myself?

**Comment by gbaranski** [comment]
All you have to do, is to use `call()` on `Server`, and since `ServerExt` has `call` handler, you can handle the logic in there.

look at the [chat server example](https://github.com/gbaranski/ezsockets/tree/master/examples/chat-server)
and change `ServerExt::call` implementation on `ChatServer` to
```rust 
let session = self.sessions.get(anything_that_identifies_sessions).unwrap(); // TODO: handle error
session.text("message sent from server"); // or session.call(), whatever
```

If you have any other questions, feel free to open a new issue :)
