### ISSUE TITLE
Sending text from on_text with a client

### ISSUE THREAD

**Issue by MoskalykA** [gbaranski/ezsockets#50]
Hi,
I can't find how to send text from on_text with a client so I'm asking if this is possible? and if so, could you please tell me how to do it?

**Comment by gbaranski** [comment]
Hi, sorry for late response, but yes it is possible of course.
I updated the `simple-client` example to make it more visible to you, check it out

https://github.com/gbaranski/ezsockets/blob/c32eae0a641f88ab1b6118fd06da025390f7057a/examples/simple-client/src/main.rs#L45

You need to pass `ezsockets::Client` to your own `Client` in order to send back messages.
If you have any more questions, let me know.

**Comment by MoskalykA** [comment]
Hi, thanks for your answer!
